### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by shaurair**
老師好，我是李若瑜
下面是可測試的網址，再麻煩老師確認，謝謝老師
http://54.203.184.226:3000/
http://54.203.184.226:3000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Separator lines are 1px only.
2. Second separator does not extend to full width in the devices where screen width>1200px.
3. There should have no space between navigator and image in the mobile devices.

**Comment by shaurair** [comment]
已修正，麻煩老師複查，謝謝老師！

**Comment by cwpeng** [comment]
Re-request review from top right corner in this pull request so that I can review for you.

**Comment by shaurair** [comment]
剛剛按下 Re-request review了，謝謝老師！

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
